// Gerador automático de cursos baseado em diários oficiais simplificados

import { Course, Module, Quiz, Question } from './types';
import { DiarioOficial, DiarioExcerpt } from './queridoDiarioMockData';

export interface GeneratedCourse {
  course: Course;
  metadata: {
    sourceType: 'diario_oficial';
    sourceDiarioId: string;
    generatedAt: Date;
    autoGenerated: boolean;
    reviewStatus: 'pending' | 'approved' | 'rejected';
  };
}

/**
 * Gera um curso completo baseado em um diário oficial simplificado
 */
export function generateCourseFromDiario(
  diario: DiarioOficial,
  excerpts: DiarioExcerpt[]
): GeneratedCourse {
  const courseId = `course-auto-${Date.now()}`;
  
  // Determinar tema principal
  const mainTheme = diario.themes[0] || 'Cidadania';
  
  // Gerar módulos (um para cada excerto)
  const modules: Module[] = excerpts.map((excerpt, index) => {
    return {
      id: `${courseId}-mod-${index + 1}`,
      title: `${excerpt.theme}: ${excerpt.subtheme}`,
      description: `Aprenda sobre ${excerpt.subtheme} de forma simples e prática`,
      duration: '15 min',
      videoUrl: `https://www.youtube.com/watch?v=dQw4w9WgXcQ`, // Placeholder
      content: excerpt.simplified_text,
      completed: false,
      unlocked: index === 0 // Apenas o primeiro módulo desbloqueado
    };
  });

  // Gerar quizzes (um para cada módulo)
  const quizzes: Quiz[] = modules.map((module, index) => {
    const excerpt = excerpts[index];
    return generateQuizForExcerpt(module.id, excerpt);
  });

  // Criar o curso
  const course: Course = {
    id: courseId,
    title: `${mainTheme}: ${diario.territory_name}`,
    description: `Entenda as novas leis e regulamentações de ${diario.territory_name} sobre ${mainTheme.toLowerCase()} de forma simples e acessível.`,
    thumbnail: getThemeImage(mainTheme),
    category: mainTheme,
    level: 'beginner',
    totalModules: modules.length,
    duration: `${modules.length * 15} min`,
    xpReward: modules.length * 50,
    modules,
    quizzes,
    tags: [...diario.themes, ...diario.subthemes, diario.state_code],
    instructor: 'IA Civilize',
    rating: 0,
    enrolledCount: 0,
    isLocked: true,
    price: 0 // Grátis pois é auto-gerado de fonte pública
  };

  return {
    course,
    metadata: {
      sourceType: 'diario_oficial',
      sourceDiarioId: diario.id,
      generatedAt: new Date(),
      autoGenerated: true,
      reviewStatus: 'pending'
    }
  };
}

/**
 * Gera um quiz baseado em um excerto simplificado
 */
function generateQuizForExcerpt(moduleId: string, excerpt: DiarioExcerpt): Quiz {
  const quizId = `quiz-${moduleId}`;
  
  // Gerar perguntas baseadas no conteúdo
  const questions: Question[] = generateQuestionsFromExcerpt(excerpt);

  return {
    id: quizId,
    moduleId,
    title: `Quiz: ${excerpt.theme}`,
    description: `Teste seus conhecimentos sobre ${excerpt.subtheme}`,
    passingScore: 75,
    questions,
    timeLimit: 300, // 5 minutos
    xpReward: 50
  };
}

/**
 * Gera perguntas de múltipla escolha baseadas no excerto
 */
function generateQuestionsFromExcerpt(excerpt: DiarioExcerpt): Question[] {
  const questions: Question[] = [];

  // Questão 1: Tema principal
  questions.push({
    id: `q1-${excerpt.id}`,
    question: `Sobre qual tema principal trata este conteúdo?`,
    options: [
      excerpt.theme,
      getRandomTheme(excerpt.theme),
      getRandomTheme(excerpt.theme),
      getRandomTheme(excerpt.theme)
    ],
    correctAnswer: 0,
    explanation: `O tema principal é ${excerpt.theme}, abordando especificamente ${excerpt.subtheme}.`
  });

  // Questão 2: Público-alvo
  questions.push({
    id: `q2-${excerpt.id}`,
    question: `Para quem essa informação é mais relevante?`,
    options: [
      excerpt.target_audience,
      'Apenas profissionais da área jurídica',
      'Somente empresários',
      'Apenas servidores públicos'
    ],
    correctAnswer: 0,
    explanation: `Esta informação foi simplificada para ${excerpt.target_audience}, tornando-a acessível para todos.`
  });

  // Questão 3: Palavras-chave
  const keyword = excerpt.keywords[0] || 'cidadania';
  questions.push({
    id: `q3-${excerpt.id}`,
    question: `Qual conceito é fundamental para entender este conteúdo?`,
    options: [
      keyword.charAt(0).toUpperCase() + keyword.slice(1),
      'Processo judicial',
      'Tributação municipal',
      'Licitação pública'
    ],
    correctAnswer: 0,
    explanation: `${keyword.charAt(0).toUpperCase() + keyword.slice(1)} é um dos conceitos-chave para compreender este assunto.`
  });

  // Questão 4: Aplicação prática
  questions.push({
    id: `q4-${excerpt.id}`,
    question: `Qual a melhor forma de aplicar esse conhecimento no dia a dia?`,
    options: [
      generatePracticalApplication(excerpt.theme),
      'Guardar a informação sem usar',
      'Compartilhar apenas com advogados',
      'Ignorar completamente'
    ],
    correctAnswer: 0,
    explanation: `O conhecimento sobre ${excerpt.theme} deve ser aplicado ativamente no seu cotidiano para exercer melhor sua cidadania.`
  });

  return questions;
}

/**
 * Gera uma aplicação prática baseada no tema
 */
function generatePracticalApplication(theme: string): string {
  const applications: { [key: string]: string } = {
    'Educação': 'Participar ativamente das decisões sobre educação na sua comunidade',
    'Saúde': 'Conhecer seus direitos ao usar o sistema de saúde público',
    'Meio Ambiente': 'Aplicar as práticas de sustentabilidade no dia a dia',
    'Transporte': 'Usar o transporte público de forma consciente e conhecer seus direitos',
    'Economia': 'Planejar melhor suas finanças pessoais',
    'Trabalho': 'Conhecer seus direitos trabalhistas e fazer valer',
    'Segurança': 'Participar de iniciativas de segurança comunitária',
    'Cultura': 'Valorizar e preservar o patrimônio cultural local'
  };

  return applications[theme] || 'Exercer ativamente sua cidadania no dia a dia';
}

/**
 * Retorna um tema aleatório diferente do fornecido (para distratores)
 */
function getRandomTheme(exclude: string): string {
  const themes = ['Educação', 'Saúde', 'Meio Ambiente', 'Transporte', 'Economia', 'Trabalho', 'Segurança', 'Cultura'];
  const filtered = themes.filter(t => t !== exclude);
  return filtered[Math.floor(Math.random() * filtered.length)];
}

/**
 * Retorna uma imagem apropriada para o tema
 */
function getThemeImage(theme: string): string {
  const images: { [key: string]: string } = {
    'Educação': 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    'Saúde': 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
    'Meio Ambiente': 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800',
    'Transporte': 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    'Economia': 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800',
    'Trabalho': 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800',
    'Segurança': 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800',
    'Cultura': 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800'
  };

  return images[theme] || 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800';
}

/**
 * Gera um artigo educativo baseado no excerto
 */
export function generateArticleFromExcerpt(excerpt: DiarioExcerpt): {
  title: string;
  content: string;
  readTime: string;
  tags: string[];
} {
  return {
    title: `Entenda: ${excerpt.subtheme}`,
    content: `
# ${excerpt.subtheme}

## 📋 O que diz a lei original:

${excerpt.original_text}

---

## 💡 Tradução simples:

${excerpt.simplified_text}

---

## 🎯 Por que isso é importante?

Este conhecimento faz parte dos seus direitos como cidadão. Quando você entende as leis da sua cidade, pode:

✅ Participar melhor das decisões públicas
✅ Cobrar seus direitos
✅ Cumprir seus deveres de forma consciente
✅ Contribuir para uma sociedade mais justa

---

## 📚 Quer saber mais?

Continue estudando outros módulos sobre ${excerpt.theme} e torne-se um cidadão cada vez mais informado!

---

**Fonte:** Diário Oficial processado e simplificado por IA
**Nível de complexidade:** ${excerpt.complexity_level === 'easy' ? 'Fácil' : excerpt.complexity_level === 'medium' ? 'Médio' : 'Avançado'}
    `,
    readTime: '5 min',
    tags: excerpt.keywords
  };
}

/**
 * Estatísticas de geração de cursos
 */
export interface CourseGenerationStats {
  totalGenerated: number;
  pending: number;
  approved: number;
  rejected: number;
  avgModulesPerCourse: number;
  avgQuestionsPerQuiz: number;
  totalStudents: number;
  avgCompletionRate: number;
}

export function getCourseGenerationStats(courses: GeneratedCourse[]): CourseGenerationStats {
  const pending = courses.filter(c => c.metadata.reviewStatus === 'pending').length;
  const approved = courses.filter(c => c.metadata.reviewStatus === 'approved').length;
  const rejected = courses.filter(c => c.metadata.reviewStatus === 'rejected').length;

  const avgModulesPerCourse = courses.reduce((sum, c) => sum + c.course.totalModules, 0) / courses.length || 0;
  const avgQuestionsPerQuiz = courses.reduce((sum, c) => {
    const totalQuestions = c.course.quizzes.reduce((qSum, quiz) => qSum + quiz.questions.length, 0);
    return sum + (totalQuestions / c.course.quizzes.length || 0);
  }, 0) / courses.length || 0;

  return {
    totalGenerated: courses.length,
    pending,
    approved,
    rejected,
    avgModulesPerCourse: Math.round(avgModulesPerCourse * 10) / 10,
    avgQuestionsPerQuiz: Math.round(avgQuestionsPerQuiz * 10) / 10,
    totalStudents: courses.reduce((sum, c) => sum + c.course.enrolledCount, 0),
    avgCompletionRate: 0.73 // Mock: 73%
  };
}
