import { Course, Badge, LeaderboardEntry } from './types';

export const mockCourses: Course[] = [
  {
    id: 'course-vida-civil',
    title: 'Vida Civil e Cartórios',
    description: 'Entenda documentos essenciais, certidões e como funcionam os cartórios no Brasil',
    thumbnail: 'https://images.unsplash.com/photo-1708793699458-0a19b74b8aeb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg',
    category: 'Cidadania',
    interest: 'tech',
    totalModules: 4,
    xpTotal: 400,
    coinPrice: 150,
    modules: [
      {
        id: 'mod-vc-1',
        title: 'Documentos Essenciais do Cidadão',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '15 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-vc-2',
        title: 'Certidões e Seus Usos',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-vc-3',
        title: 'Como Funciona um Cartório',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-vc-4',
        title: 'Registro Civil e Sucessões',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-vc-1',
        moduleId: 'mod-vc-1',
        questions: [
          {
            id: 'q-vc-1',
            question: 'Qual documento é obrigatório para todo cidadão brasileiro?',
            options: ['Passaporte', 'CPF', 'CNH', 'Título de Eleitor'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-vc-2',
            question: 'A partir de quantos anos o CPF é obrigatório?',
            options: ['Ao nascer', 'Aos 16 anos', 'Aos 18 anos', 'Não há idade mínima'],
            correctAnswer: 3,
            xpReward: 25,
          },
          {
            id: 'q-vc-3',
            question: 'O que é RG?',
            options: ['Registro Geral', 'Registro de Garantia', 'Regimento Geral', 'Requisito Geral'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-vc-4',
            question: 'Onde se emite a Certidão de Nascimento?',
            options: ['Hospital', 'Cartório', 'Prefeitura', 'Fórum'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-vc-2',
        moduleId: 'mod-vc-2',
        questions: [
          {
            id: 'q-vc-5',
            question: 'Para que serve a Certidão de Antecedentes Criminais?',
            options: ['Comprovar identidade', 'Comprovar ausência de crimes', 'Registrar endereço', 'Votar'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-vc-6',
            question: 'Onde emitir Certidão Negativa de Débitos?',
            options: ['Cartório', 'Receita Federal', 'Banco', 'Correios'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-vc-7',
            question: 'Certidão de Óbito é emitida em qual cartório?',
            options: ['Notas', 'Registro Civil', 'Imóveis', 'Títulos'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-vc-8',
            question: 'Certidões têm prazo de validade?',
            options: ['Sempre', 'Nunca', 'Depende do tipo', 'Apenas para concursos'],
            correctAnswer: 2,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-vc-3',
        moduleId: 'mod-vc-3',
        questions: [
          {
            id: 'q-vc-9',
            question: 'Quantos tipos principais de cartórios existem?',
            options: ['2', '4', '6', '8'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-vc-10',
            question: 'Qual cartório registra compra e venda de imóveis?',
            options: ['Registro Civil', 'Registro de Imóveis', 'Notas', 'Títulos'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-vc-11',
            question: 'O que é um Tabelião?',
            options: ['Funcionário público', 'Advogado especializado', 'Profissional do direito com delegação', 'Juiz'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-vc-12',
            question: 'Cartórios podem recusar atendimento?',
            options: ['Nunca', 'Apenas com justificativa legal', 'Sempre que quiserem', 'Depende da região'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-vc-4',
        moduleId: 'mod-vc-4',
        questions: [
          {
            id: 'q-vc-13',
            question: 'O que é inventário?',
            options: ['Lista de bens', 'Processo de divisão de herança', 'Tipo de testamento', 'Certidão de óbito'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-vc-14',
            question: 'Inventário pode ser feito em cartório?',
            options: ['Sim, sempre', 'Não, apenas no fórum', 'Sim, em casos específicos', 'Depende do valor'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-vc-15',
            question: 'O que é Registro Tardio de Nascimento?',
            options: ['Registro após 1 ano', 'Registro após 15 dias', 'Registro de adultos sem certidão', 'Registro online'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-vc-16',
            question: 'União estável pode ser registrada em cartório?',
            options: ['Sim', 'Não', 'Apenas com advogado', 'Apenas no fórum'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'course-saude',
    title: 'Saúde, Educação e Direitos Sociais',
    description: 'Conheça seus direitos no SUS, na educação pública e nos programas sociais',
    thumbnail: 'https://images.unsplash.com/photo-1517120026326-d87759a7b63b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg',
    category: 'Cidadania',
    interest: 'business',
    totalModules: 4,
    xpTotal: 400,
    coinPrice: 200,
    modules: [
      {
        id: 'mod-se-1',
        title: 'Direito à Saúde e o SUS',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-se-2',
        title: 'Educação Pública e Gratuita',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-se-3',
        title: 'Programas Sociais e Assistência',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-se-4',
        title: 'Direitos da Pessoa com Deficiência',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-se-1',
        moduleId: 'mod-se-1',
        questions: [
          {
            id: 'q-se-1',
            question: 'O SUS é universal e gratuito?',
            options: ['Sim', 'Não', 'Apenas para brasileiros', 'Apenas para baixa renda'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-se-2',
            question: 'Qual emenda constitucional criou o SUS?',
            options: ['EC 88', 'Constituição de 1988', 'Lei 8080', 'Decreto 90'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-se-3',
            question: 'O que fazer se negarem atendimento no SUS?',
            options: ['Desistir', 'Ir a particular', 'Denunciar à Ouvidoria', 'Pagar propina'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-se-4',
            question: 'O SUS oferece medicamentos gratuitos?',
            options: ['Sim', 'Não', 'Apenas alguns', 'Depende da cidade'],
            correctAnswer: 2,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-se-2',
        moduleId: 'mod-se-2',
        questions: [
          {
            id: 'q-se-5',
            question: 'A educação básica é obrigatória e gratuita?',
            options: ['Sim', 'Não', 'Apenas até 14 anos', 'Apenas fundamental'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-se-6',
            question: 'Até que idade a educação é direito garantido?',
            options: ['14 anos', '17 anos', '21 anos', 'Sem limite'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-se-7',
            question: 'O que é o ENEM?',
            options: ['Exame Nacional do Ensino Médio', 'Educação Nacional', 'Exame de Medicina', 'Ensino Militar'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-se-8',
            question: 'Escola pode reter material escolar por falta de pagamento?',
            options: ['Sim', 'Não', 'Depende', 'Apenas particular'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-se-3',
        moduleId: 'mod-se-3',
        questions: [
          {
            id: 'q-se-9',
            question: 'O que é o Bolsa Família?',
            options: ['Programa de transferência de renda', 'Bolsa de estudos', 'Empréstimo', 'Financiamento'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-se-10',
            question: 'Como se inscrever no CadÚnico?',
            options: ['Online', 'CRAS mais próximo', 'Banco', 'Correios'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-se-11',
            question: 'O que é BPC?',
            options: ['Banco Popular', 'Benefício de Prestação Continuada', 'Bolsa Cidadã', 'Cadastro'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-se-12',
            question: 'Quem tem direito ao Auxílio Brasil?',
            options: ['Todos', 'Famílias em vulnerabilidade', 'Apenas idosos', 'Desempregados'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-se-4',
        moduleId: 'mod-se-4',
        questions: [
          {
            id: 'q-se-13',
            question: 'O que garante a Lei Brasileira de Inclusão?',
            options: ['Direitos iguais', 'Acessibilidade', 'Autonomia', 'Todas as anteriores'],
            correctAnswer: 3,
            xpReward: 25,
          },
          {
            id: 'q-se-14',
            question: 'Vagas prioritárias são obrigatórias?',
            options: ['Sim', 'Não', 'Depende', 'Apenas em hospitais'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-se-15',
            question: 'PCD tem direito a passe livre no transporte?',
            options: ['Sim, sempre', 'Depende da renda', 'Não', 'Apenas idosos'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-se-16',
            question: 'O que é o Estatuto da Pessoa com Deficiência?',
            options: ['Lei 13.146/2015', 'Decreto 88', 'Emenda 99', 'Portaria'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'course-trabalho',
    title: 'Trabalho, Renda e Previdência',
    description: 'Aprenda sobre direitos trabalhistas, CLT, aposentadoria e empreendedorismo',
    thumbnail: 'https://images.unsplash.com/photo-1633113214866-961efd94c84d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg',
    category: 'Cidadania',
    interest: 'design',
    totalModules: 4,
    xpTotal: 400,
    coinPrice: 180,
    modules: [
      {
        id: 'mod-tr-1',
        title: 'Direitos Trabalhistas e CLT',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '25 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-tr-2',
        title: 'FGTS, Seguro-Desemprego e Direitos',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-tr-3',
        title: 'Previdência Social e Aposentadoria',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-tr-4',
        title: 'MEI e Empreendedorismo',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-tr-1',
        moduleId: 'mod-tr-1',
        questions: [
          {
            id: 'q-tr-1',
            question: 'Quantas horas é a jornada de trabalho semanal padrão?',
            options: ['40 horas', '44 horas', '48 horas', '50 horas'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-2',
            question: 'Férias são de quantos dias?',
            options: ['15', '20', '30', '45'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-tr-3',
            question: 'O que é 13º salário?',
            options: ['Bônus', 'Gratificação de Natal', 'Extra', 'Comissão'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-4',
            question: 'Hora extra tem adicional de quanto?',
            options: ['25%', '50%', '100%', 'Livre negociação'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-tr-2',
        moduleId: 'mod-tr-2',
        questions: [
          {
            id: 'q-tr-5',
            question: 'O que é FGTS?',
            options: ['Fundo de Garantia do Tempo de Serviço', 'Fundo Geral', 'Férias Garantidas', 'Fundação'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-tr-6',
            question: 'Quanto o empregador deposita de FGTS?',
            options: ['5%', '8%', '10%', '15%'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-7',
            question: 'Quantas parcelas tem o seguro-desemprego?',
            options: ['2 a 4', '3 a 5', '5 a 7', '6 a 12'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-8',
            question: 'Demissão sem justa causa dá direito a FGTS?',
            options: ['Sim', 'Não', 'Às vezes', 'Depende'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-tr-3',
        moduleId: 'mod-tr-3',
        questions: [
          {
            id: 'q-tr-9',
            question: 'Idade mínima para aposentadoria de mulheres?',
            options: ['55 anos', '60 anos', '62 anos', '65 anos'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-tr-10',
            question: 'E para homens?',
            options: ['60 anos', '62 anos', '65 anos', '70 anos'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-tr-11',
            question: 'Tempo mínimo de contribuição?',
            options: ['10 anos', '15 anos', '20 anos', '25 anos'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-12',
            question: 'O que é INSS?',
            options: ['Instituto Nacional do Seguro Social', 'Instituição Nacional', 'Índice Social', 'Imposto'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-tr-4',
        moduleId: 'mod-tr-4',
        questions: [
          {
            id: 'q-tr-13',
            question: 'O que é MEI?',
            options: ['Microempreendedor Individual', 'Micro Empresa', 'Empreendedor Informal', 'Empresa'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-tr-14',
            question: 'Limite de faturamento anual do MEI?',
            options: ['R$ 60 mil', 'R$ 81 mil', 'R$ 100 mil', 'R$ 120 mil'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-15',
            question: 'MEI pode ter quantos funcionários?',
            options: ['Nenhum', '1', '2', '5'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-tr-16',
            question: 'Como se formalizar como MEI?',
            options: ['Portal do Empreendedor', 'Cartório', 'Junta Comercial', 'Receita Federal'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'course-consumo',
    title: 'Consumo, Bancos e Serviços Digitais',
    description: 'Conheça o Código de Defesa do Consumidor, seus direitos bancários e segurança digital',
    thumbnail: 'https://images.unsplash.com/photo-1627997394689-e1c6343c91bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg',
    category: 'Cidadania',
    interest: 'science',
    totalModules: 4,
    xpTotal: 400,
    coinPrice: 220,
    modules: [
      {
        id: 'mod-co-1',
        title: 'Código de Defesa do Consumidor',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-co-2',
        title: 'Direitos em Compras Online',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-co-3',
        title: 'Bancos, Financiamentos e Crédito',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-co-4',
        title: 'Segurança Digital e Dados Pessoais',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-co-1',
        moduleId: 'mod-co-1',
        questions: [
          {
            id: 'q-co-1',
            question: 'O CDC protege quem?',
            options: ['Empresas', 'Consumidores', 'Governos', 'Bancos'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-2',
            question: 'Prazo para desistir de compra online?',
            options: ['3 dias', '7 dias', '15 dias', '30 dias'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-3',
            question: 'O que é garantia legal?',
            options: ['30 dias para não duráveis, 90 para duráveis', '1 ano', '6 meses', 'Depende'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-co-4',
            question: 'Onde denunciar problemas de consumo?',
            options: ['Polícia', 'Procon', 'Detran', 'Receita'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-co-2',
        moduleId: 'mod-co-2',
        questions: [
          {
            id: 'q-co-5',
            question: 'Direito de arrependimento vale para lojas físicas?',
            options: ['Sim', 'Não', 'Depende', 'Às vezes'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-6',
            question: 'Produto com defeito, prazo para troca?',
            options: ['Imediato', '7 dias', '30 dias', '90 dias'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q-co-7',
            question: 'Frete grátis com valor mínimo é propaganda enganosa?',
            options: ['Sim', 'Não', 'Depende da divulgação', 'Sempre'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-8',
            question: 'E-commerce pode cobrar mais no cartão?',
            options: ['Sim', 'Não', 'Depende', 'Até 5%'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-co-3',
        moduleId: 'mod-co-3',
        questions: [
          {
            id: 'q-co-9',
            question: 'Banco pode negativar sem aviso prévio?',
            options: ['Sim', 'Não', 'Depende', 'Após 30 dias'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-10',
            question: 'O que é CET?',
            options: ['Custo Efetivo Total', 'Cartão de Crédito', 'Central', 'Cobrança'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-co-11',
            question: 'Banco pode cobrar tarifa de manutenção em conta salário?',
            options: ['Sim', 'Não', 'Depende', 'Até R$ 10'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-12',
            question: 'Onde consultar score de crédito gratuitamente?',
            options: ['Banco', 'Serasa, Boa Vista', 'Receita', 'Procon'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-co-4',
        moduleId: 'mod-co-4',
        questions: [
          {
            id: 'q-co-13',
            question: 'O que é LGPD?',
            options: ['Lei Geral de Proteção de Dados', 'Lei de Dados', 'Licença', 'Legislação'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-co-14',
            question: 'Empresa pode compartilhar meus dados sem consentimento?',
            options: ['Sim', 'Não', 'Depende', 'Com parceiros'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-15',
            question: 'Como solicitar exclusão de dados?',
            options: ['Não é possível', 'Diretamente à empresa', 'Justiça', 'Polícia'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-co-16',
            question: 'O que fazer se sofrer vazamento de dados?',
            options: ['Nada', 'Denunciar à ANPD', 'Trocar senhas', 'Ambas B e C'],
            correctAnswer: 3,
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'course-justica',
    title: 'Justiça, Segurança e Direitos Humanos',
    description: 'Entenda o sistema judiciário, seus direitos civis e como denunciar violações',
    thumbnail: 'https://images.unsplash.com/photo-1640655367482-fa9797fe1258?crop=entropy&cs=tinysrgb&fit=max&fm=jpg',
    category: 'Cidadania',
    interest: 'languages',
    totalModules: 4,
    xpTotal: 400,
    coinPrice: 190,
    modules: [
      {
        id: 'mod-ju-1',
        title: 'Sistema Judiciário Brasileiro',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-ju-2',
        title: 'Direitos e Garantias Fundamentais',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-ju-3',
        title: 'Segurança Pública e Seus Direitos',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-ju-4',
        title: 'Direitos Humanos e Cidadania',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-ju-1',
        moduleId: 'mod-ju-1',
        questions: [
          {
            id: 'q-ju-1',
            question: 'Quantos poderes tem o Brasil?',
            options: ['2', '3', '4', '5'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-ju-2',
            question: 'Quem julga causas de até 40 salários mínimos?',
            options: ['STF', 'Juizado Especial', 'Tribunal', 'Fórum'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-ju-3',
            question: 'O que é STF?',
            options: ['Supremo Tribunal Federal', 'Sistema Tributário', 'Serviço Federal', 'Superior Tribunal'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ju-4',
            question: 'Justiça gratuita existe?',
            options: ['Sim, para baixa renda', 'Não', 'Apenas criminal', 'Depende'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-ju-2',
        moduleId: 'mod-ju-2',
        questions: [
          {
            id: 'q-ju-5',
            question: 'Liberdade de expressão é absoluta?',
            options: ['Sim', 'Não, tem limites legais', 'Depende', 'Apenas para políticos'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-ju-6',
            question: 'O que é Habeas Corpus?',
            options: ['Garantia de liberdade', 'Prisão', 'Multa', 'Processo'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ju-7',
            question: 'Brasileiro pode ser extraditado?',
            options: ['Sim, sempre', 'Não, nunca', 'Depende do caso', 'Apenas naturalizado'],
            correctAnswer: 3,
            xpReward: 25,
          },
          {
            id: 'q-ju-8',
            question: 'Direito ao silêncio existe?',
            options: ['Sim', 'Não', 'Apenas para réus', 'Depende'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-ju-3',
        moduleId: 'mod-ju-3',
        questions: [
          {
            id: 'q-ju-9',
            question: 'Policial pode revistar sem mandado?',
            options: ['Sim, em flagrante', 'Não, nunca', 'Sempre', 'Apenas à noite'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ju-10',
            question: 'O que fazer se presenciar abuso policial?',
            options: ['Nada', 'Filmar e denunciar', 'Intervir', 'Fugir'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-ju-11',
            question: 'Onde denunciar violência policial?',
            options: ['Ouvidoria, Ministério Público', 'Mídia', 'Redes sociais', 'Delegacia'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ju-12',
            question: 'Prisão precisa de mandado?',
            options: ['Sempre', 'Não em flagrante', 'Nunca', 'Depende da hora'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-ju-4',
        moduleId: 'mod-ju-4',
        questions: [
          {
            id: 'q-ju-13',
            question: 'O que são Direitos Humanos?',
            options: ['Direitos universais', 'Apenas no Brasil', 'Proteção de criminosos', 'Lei específica'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ju-14',
            question: 'Discriminação é crime?',
            options: ['Sim', 'Não', 'Depende', 'Apenas racial'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ju-15',
            question: 'O que é Disque 100?',
            options: ['Emergência', 'Denúncia de violação de direitos humanos', 'Polícia', 'Bombeiros'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q-ju-16',
            question: 'Refugiados têm direitos no Brasil?',
            options: ['Sim', 'Não', 'Apenas temporário', 'Depende do país'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'course-cidade',
    title: 'Cidade, Meio Ambiente e Participação Pública',
    description: 'Aprenda sobre urbanismo, meio ambiente e como participar das decisões públicas',
    thumbnail: 'https://images.unsplash.com/photo-1693669507124-2bee07b78068?crop=entropy&cs=tinysrgb&fit=max&fm=jpg',
    category: 'Cidadania',
    interest: 'personal',
    totalModules: 4,
    xpTotal: 400,
    coinPrice: 210,
    modules: [
      {
        id: 'mod-ci-1',
        title: 'Direito à Cidade e Moradia',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-ci-2',
        title: 'Meio Ambiente e Sustentabilidade',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-ci-3',
        title: 'Participação Popular e Democracia',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-ci-4',
        title: 'Ouvidorias, Consultas e Audiências Públicas',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-ci-1',
        moduleId: 'mod-ci-1',
        questions: [
          {
            id: 'q-ci-1',
            question: 'Moradia é direito fundamental?',
            options: ['Sim', 'Não', 'Depende', 'Apenas para baixa renda'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-2',
            question: 'O que é Plano Diretor?',
            options: ['Lei de planejamento urbano', 'Projeto de casa', 'Mapa da cidade', 'Código de obras'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-3',
            question: 'IPTU financia o quê?',
            options: ['Serviços municipais', 'Governo federal', 'Estados', 'Nada'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-4',
            question: 'Desapropriação é legal?',
            options: ['Sim, com indenização', 'Não', 'Sempre', 'Nunca'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-ci-2',
        moduleId: 'mod-ci-2',
        questions: [
          {
            id: 'q-ci-5',
            question: 'Meio ambiente equilibrado é direito?',
            options: ['Sim', 'Não', 'Depende', 'Apenas futuras gerações'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-6',
            question: 'Como denunciar crime ambiental?',
            options: ['Ibama, MP', 'Polícia Civil', 'Prefeitura', 'Bombeiros'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-7',
            question: 'Coleta seletiva é obrigatória?',
            options: ['Em algumas cidades', 'Não', 'Sim, sempre', 'Apenas para empresas'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-8',
            question: 'O que é licenciamento ambiental?',
            options: ['Autorização para obras/atividades', 'Multa', 'Taxa', 'Imposto'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-ci-3',
        moduleId: 'mod-ci-3',
        questions: [
          {
            id: 'q-ci-9',
            question: 'Como funciona uma consulta pública?',
            options: ['Cidadãos opinam sobre projetos', 'Votação', 'Eleição', 'Referendo'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-10',
            question: 'O que é orçamento participativo?',
            options: ['Cidadãos decidem parte do orçamento', 'Orçamento público', 'Conta da prefeitura', 'Imposto'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-11',
            question: 'Cidadão pode propor leis?',
            options: ['Sim, via iniciativa popular', 'Não', 'Apenas vereadores', 'Depende'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-12',
            question: 'Quantas assinaturas para projeto de lei popular federal?',
            options: ['1 mil', '10 mil', '100 mil', '1% do eleitorado (≈ 1,5 milhão)'],
            correctAnswer: 3,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-ci-4',
        moduleId: 'mod-ci-4',
        questions: [
          {
            id: 'q-ci-13',
            question: 'O que é Ouvidoria?',
            options: ['Canal de comunicação com poder público', 'Advogado', 'Juiz', 'Promotor'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-14',
            question: 'Audiência pública é obrigatória?',
            options: ['Sim, em vários casos', 'Não', 'Sempre', 'Nunca'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-15',
            question: 'Onde acessar gastos públicos?',
            options: ['Portais de transparência', 'Não é público', 'Apenas com advogado', 'Jornais'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q-ci-16',
            question: 'O que é LAI (Lei de Acesso à Informação)?',
            options: ['Direito a informações públicas', 'Lei ambiental', 'Imposto', 'Código penal'],
            correctAnswer: 0,
            xpReward: 25,
          },
        ],
      },
    ],
  },
];

export const allBadges: Badge[] = [
  {
    id: 'badge-1',
    name: 'Primeiro Passo',
    description: 'Complete seu primeiro módulo',
    icon: '🎯',
    unlocked: false,
    requirement: 'Complete 1 módulo',
  },
  {
    id: 'badge-2',
    name: 'Estudante Dedicado',
    description: 'Complete 5 módulos',
    icon: '📚',
    unlocked: false,
    requirement: 'Complete 5 módulos',
  },
  {
    id: 'badge-3',
    name: 'Mestre do Quiz',
    description: 'Acerte todos as questões de um quiz',
    icon: '🏆',
    unlocked: false,
    requirement: 'Pontuação perfeita em um quiz',
  },
  {
    id: 'badge-4',
    name: 'Conquistador',
    description: 'Complete seu primeiro curso',
    icon: '⭐',
    unlocked: false,
    requirement: 'Complete 1 curso',
  },
  {
    id: 'badge-5',
    name: 'Expert',
    description: 'Alcance o nível 5',
    icon: '💎',
    unlocked: false,
    requirement: 'Alcance nível 5',
  },
  {
    id: 'badge-6',
    name: 'Maratonista',
    description: 'Estude por 7 dias seguidos',
    icon: '🔥',
    unlocked: false,
    requirement: 'Streak de 7 dias',
  },
  {
    id: 'badge-7',
    name: 'Colecionador',
    description: 'Complete 3 cursos',
    icon: '🎓',
    unlocked: false,
    requirement: 'Complete 3 cursos',
  },
  {
    id: 'badge-8',
    name: 'Top 10',
    description: 'Entre no top 10 do ranking',
    icon: '🥇',
    unlocked: false,
    requirement: 'Ranking top 10',
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    userId: '1',
    name: 'Ana Silva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    xp: 2450,
    level: 12,
    coursesCompleted: 5,
  },
  {
    userId: '2',
    name: 'Carlos Souza',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    xp: 2100,
    level: 10,
    coursesCompleted: 4,
  },
  {
    userId: '3',
    name: 'Beatriz Costa',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Beatriz',
    xp: 1950,
    level: 9,
    coursesCompleted: 4,
  },
  {
    userId: '4',
    name: 'Daniel Lima',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    xp: 1720,
    level: 8,
    coursesCompleted: 3,
  },
  {
    userId: '5',
    name: 'Eduarda Mendes',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eduarda',
    xp: 1500,
    level: 7,
    coursesCompleted: 3,
  },
  {
    userId: 'current',
    name: 'Você',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Current',
    xp: 850,
    level: 4,
    coursesCompleted: 1,
  },
  {
    userId: '7',
    name: 'Fernando Rocha',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fernando',
    xp: 680,
    level: 3,
    coursesCompleted: 1,
  },
  {
    userId: '8',
    name: 'Gabriela Santos',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gabriela',
    xp: 520,
    level: 2,
    coursesCompleted: 1,
  },
  {
    userId: '9',
    name: 'Hugo Pereira',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hugo',
    xp: 340,
    level: 1,
    coursesCompleted: 0,
  },
  {
    userId: '10',
    name: 'Isabela Alves',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabela',
    xp: 220,
    level: 1,
    coursesCompleted: 0,
  },
];