import { Course, Badge, LeaderboardEntry } from './types';

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Introdução ao JavaScript',
    description: 'Aprenda os fundamentos da linguagem JavaScript do zero',
    thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&h=600&fit=crop',
    category: 'Programação',
    totalModules: 4,
    xpTotal: 400,
    modules: [
      {
        id: 'mod-1-1',
        title: 'Variáveis e Tipos de Dados',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '15 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-1-2',
        title: 'Operadores e Expressões',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-1-3',
        title: 'Estruturas de Controle',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '25 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-1-4',
        title: 'Funções e Escopo',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '30 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-1-1',
        moduleId: 'mod-1-1',
        questions: [
          {
            id: 'q1',
            question: 'Qual palavra-chave é usada para declarar uma variável que não pode ser reatribuída?',
            options: ['var', 'let', 'const', 'static'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q2',
            question: 'Qual é o tipo de dado do valor "true"?',
            options: ['string', 'number', 'boolean', 'object'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q3',
            question: 'Como declarar uma variável que pode mudar de valor?',
            options: ['const x = 10', 'let x = 10', 'final x = 10', 'static x = 10'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q4',
            question: 'Qual símbolo é usado para comentários de uma linha em JavaScript?',
            options: ['#', '//', '/*', '--'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-1-2',
        moduleId: 'mod-1-2',
        questions: [
          {
            id: 'q5',
            question: 'Qual operador é usado para comparação de igualdade estrita?',
            options: ['==', '===', '=', '!='],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q6',
            question: 'Qual é o resultado de 5 + "5" em JavaScript?',
            options: ['10', '"55"', '55', 'Error'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q7',
            question: 'Qual operador lógico representa "E"?',
            options: ['||', '&&', '!', '=='],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q8',
            question: 'Qual é o operador de resto da divisão?',
            options: ['/', '%', '//', 'mod'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-1-3',
        moduleId: 'mod-1-3',
        questions: [
          {
            id: 'q9',
            question: 'Qual estrutura é usada para executar código repetidamente?',
            options: ['if', 'switch', 'for', 'return'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q10',
            question: 'Qual palavra-chave interrompe um loop?',
            options: ['stop', 'exit', 'break', 'return'],
            correctAnswer: 2,
            xpReward: 25,
          },
          {
            id: 'q11',
            question: 'Qual estrutura permite múltiplas condições?',
            options: ['if-else', 'switch', 'while', 'both a and b'],
            correctAnswer: 3,
            xpReward: 25,
          },
          {
            id: 'q12',
            question: 'Qual palavra-chave pula para a próxima iteração do loop?',
            options: ['skip', 'next', 'continue', 'pass'],
            correctAnswer: 2,
            xpReward: 25,
          },
        ],
      },
      {
        id: 'quiz-1-4',
        moduleId: 'mod-1-4',
        questions: [
          {
            id: 'q13',
            question: 'Como declarar uma função em JavaScript?',
            options: ['function myFunc() {}', 'def myFunc() {}', 'func myFunc() {}', 'void myFunc() {}'],
            correctAnswer: 0,
            xpReward: 25,
          },
          {
            id: 'q14',
            question: 'Qual palavra-chave retorna um valor de uma função?',
            options: ['send', 'return', 'output', 'give'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q15',
            question: 'O que é escopo de variável?',
            options: ['Tipo da variável', 'Onde a variável pode ser acessada', 'Valor da variável', 'Nome da variável'],
            correctAnswer: 1,
            xpReward: 25,
          },
          {
            id: 'q16',
            question: 'Arrow functions são declaradas com qual símbolo?',
            options: ['->', '=>', '-->', '->|'],
            correctAnswer: 1,
            xpReward: 25,
          },
        ],
      },
    ],
  },
  {
    id: 'course-2',
    title: 'React para Iniciantes',
    description: 'Domine os fundamentos do React e crie aplicações interativas',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=600&fit=crop',
    category: 'Programação',
    totalModules: 3,
    xpTotal: 300,
    modules: [
      {
        id: 'mod-2-1',
        title: 'Componentes e Props',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-2-2',
        title: 'Estado e Ciclo de Vida',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '22 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-2-3',
        title: 'Hooks Essenciais',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '28 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-2-1',
        moduleId: 'mod-2-1',
        questions: [
          {
            id: 'q17',
            question: 'O que são Props em React?',
            options: ['Propriedades do browser', 'Dados passados entre componentes', 'Estilos CSS', 'Funções do React'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q18',
            question: 'Como criar um componente funcional?',
            options: ['class MyComponent {}', 'function MyComponent() {}', 'component MyComponent() {}', 'create MyComponent() {}'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q19',
            question: 'Props são somente leitura?',
            options: ['Sim', 'Não', 'Depende', 'Às vezes'],
            correctAnswer: 0,
            xpReward: 34,
          },
        ],
      },
      {
        id: 'quiz-2-2',
        moduleId: 'mod-2-2',
        questions: [
          {
            id: 'q20',
            question: 'Qual método força a re-renderização de um componente de classe?',
            options: ['this.update()', 'this.render()', 'this.setState()', 'this.forceUpdate()'],
            correctAnswer: 2,
            xpReward: 33,
          },
          {
            id: 'q21',
            question: 'Qual método é chamado após o componente ser montado?',
            options: ['componentWillMount', 'componentDidMount', 'componentMounted', 'onMount'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q22',
            question: 'O estado pode ser modificado diretamente?',
            options: ['Sim', 'Não', 'Somente em classes', 'Somente em hooks'],
            correctAnswer: 1,
            xpReward: 34,
          },
        ],
      },
      {
        id: 'quiz-2-3',
        moduleId: 'mod-2-3',
        questions: [
          {
            id: 'q23',
            question: 'Qual hook é usado para gerenciar estado?',
            options: ['useEffect', 'useState', 'useContext', 'useReducer'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q24',
            question: 'Qual hook substitui componentDidMount?',
            options: ['useState', 'useEffect', 'useMount', 'useLifecycle'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q25',
            question: 'Hooks podem ser usados em componentes de classe?',
            options: ['Sim', 'Não', 'Somente alguns', 'Depende da versão'],
            correctAnswer: 1,
            xpReward: 34,
          },
        ],
      },
    ],
  },
  {
    id: 'course-3',
    title: 'Design de UI/UX',
    description: 'Aprenda os princípios fundamentais de design de interfaces',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
    category: 'Design',
    totalModules: 3,
    xpTotal: 300,
    modules: [
      {
        id: 'mod-3-1',
        title: 'Princípios de Design',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '20 min',
        completed: false,
        unlocked: true,
      },
      {
        id: 'mod-3-2',
        title: 'Teoria das Cores',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '18 min',
        completed: false,
        unlocked: false,
      },
      {
        id: 'mod-3-3',
        title: 'Tipografia e Layout',
        videoUrl: 'https://www.youtube.com/embed/Ptbk2af68e8',
        duration: '25 min',
        completed: false,
        unlocked: false,
      },
    ],
    quizzes: [
      {
        id: 'quiz-3-1',
        moduleId: 'mod-3-1',
        questions: [
          {
            id: 'q26',
            question: 'Qual é o princípio de design que cria diferença visual?',
            options: ['Contraste', 'Alinhamento', 'Proximidade', 'Repetição'],
            correctAnswer: 0,
            xpReward: 33,
          },
          {
            id: 'q27',
            question: 'O que significa hierarquia visual?',
            options: ['Ordem de importância', 'Cor do elemento', 'Tamanho da fonte', 'Posição na tela'],
            correctAnswer: 0,
            xpReward: 33,
          },
          {
            id: 'q28',
            question: 'Qual princípio organiza elementos relacionados juntos?',
            options: ['Contraste', 'Alinhamento', 'Proximidade', 'Equilíbrio'],
            correctAnswer: 2,
            xpReward: 34,
          },
        ],
      },
      {
        id: 'quiz-3-2',
        moduleId: 'mod-3-2',
        questions: [
          {
            id: 'q29',
            question: 'Cores complementares ficam onde no círculo cromático?',
            options: ['Lado a lado', 'Opostas', 'Próximas', 'Alternadas'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q30',
            question: 'Qual sistema de cores é usado em telas?',
            options: ['CMYK', 'RGB', 'Pantone', 'HSL'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q31',
            question: 'O que significa contraste de cor?',
            options: ['Cores iguais', 'Diferença entre cores', 'Mistura de cores', 'Tons de cinza'],
            correctAnswer: 1,
            xpReward: 34,
          },
        ],
      },
      {
        id: 'quiz-3-3',
        moduleId: 'mod-3-3',
        questions: [
          {
            id: 'q32',
            question: 'Qual unidade é relativa ao tamanho da fonte do elemento pai?',
            options: ['px', 'em', 'pt', 'cm'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q33',
            question: 'O que é kerning?',
            options: ['Espaço entre linhas', 'Espaço entre letras', 'Tamanho da fonte', 'Estilo da fonte'],
            correctAnswer: 1,
            xpReward: 33,
          },
          {
            id: 'q34',
            question: 'Qual é a largura ideal de linha de texto para leitura?',
            options: ['20-30 caracteres', '45-75 caracteres', '100-120 caracteres', 'Sem limite'],
            correctAnswer: 1,
            xpReward: 34,
          },
        ],
      },
    ],
  },
];

export const allBadges: Badge[] = [
  {
    id: 'badge-1',
    name: 'Primeiro Passo',
    description: 'Complete seu primeiro módulo',
    icon: '🎯',
    unlocked: false,
    requirement: 'Complete 1 módulo',
  },
  {
    id: 'badge-2',
    name: 'Estudante Dedicado',
    description: 'Complete 5 módulos',
    icon: '📚',
    unlocked: false,
    requirement: 'Complete 5 módulos',
  },
  {
    id: 'badge-3',
    name: 'Mestre do Quiz',
    description: 'Acerte todos as questões de um quiz',
    icon: '🏆',
    unlocked: false,
    requirement: 'Pontuação perfeita em um quiz',
  },
  {
    id: 'badge-4',
    name: 'Conquistador',
    description: 'Complete seu primeiro curso',
    icon: '⭐',
    unlocked: false,
    requirement: 'Complete 1 curso',
  },
  {
    id: 'badge-5',
    name: 'Expert',
    description: 'Alcance o nível 5',
    icon: '💎',
    unlocked: false,
    requirement: 'Alcance nível 5',
  },
  {
    id: 'badge-6',
    name: 'Maratonista',
    description: 'Estude por 7 dias seguidos',
    icon: '🔥',
    unlocked: false,
    requirement: 'Streak de 7 dias',
  },
  {
    id: 'badge-7',
    name: 'Colecionador',
    description: 'Complete 3 cursos',
    icon: '🎓',
    unlocked: false,
    requirement: 'Complete 3 cursos',
  },
  {
    id: 'badge-8',
    name: 'Top 10',
    description: 'Entre no top 10 do ranking',
    icon: '🥇',
    unlocked: false,
    requirement: 'Ranking top 10',
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    userId: '1',
    name: 'Ana Silva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ana',
    xp: 2450,
    level: 12,
    coursesCompleted: 5,
  },
  {
    userId: '2',
    name: 'Carlos Souza',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
    xp: 2100,
    level: 10,
    coursesCompleted: 4,
  },
  {
    userId: '3',
    name: 'Beatriz Costa',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Beatriz',
    xp: 1950,
    level: 9,
    coursesCompleted: 4,
  },
  {
    userId: '4',
    name: 'Daniel Lima',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
    xp: 1720,
    level: 8,
    coursesCompleted: 3,
  },
  {
    userId: '5',
    name: 'Eduarda Mendes',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eduarda',
    xp: 1500,
    level: 7,
    coursesCompleted: 3,
  },
  {
    userId: 'current',
    name: 'Você',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Current',
    xp: 850,
    level: 4,
    coursesCompleted: 1,
  },
  {
    userId: '7',
    name: 'Fernando Rocha',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fernando',
    xp: 680,
    level: 3,
    coursesCompleted: 1,
  },
  {
    userId: '8',
    name: 'Gabriela Santos',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gabriela',
    xp: 520,
    level: 2,
    coursesCompleted: 1,
  },
  {
    userId: '9',
    name: 'Hugo Pereira',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hugo',
    xp: 340,
    level: 1,
    coursesCompleted: 0,
  },
  {
    userId: '10',
    name: 'Isabela Alves',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabela',
    xp: 220,
    level: 1,
    coursesCompleted: 0,
  },
];
